import json
import httpx
from typing import List, Dict, Any, AsyncGenerator, Optional

from backend.app.providers.base import AIProvider, LLMMessage, LLMResponse
from backend.app.config import settings
from backend.app.core.logging import logger


class OpenAIProvider(AIProvider):
    def __init__(self, api_key: Optional[str] = None, base_url: Optional[str] = None):
        super().__init__(
            api_key=api_key or settings.OPENAI_API_KEY,
            base_url=base_url or settings.OPENAI_API_BASE
        )

    async def generate(
        self,
        messages: List[LLMMessage],
        model: str,
        temperature: float = 0.7,
        max_tokens: int = 4096,
        tools: Optional[List[Dict[str, Any]]] = None,
        **kwargs: Any
    ) -> LLMResponse:
        if not self.api_key:
            logger.warning("OPENAI_API_KEY not set, using local engine response")
            last_msg = messages[-1].content if messages else ""
            return LLMResponse(
                content=f"[CodeMind AI Local Engine] Response to: {last_msg[:100]}",
                model=model
            )

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": model,
            "messages": [msg.model_dump(exclude_none=True) for msg in messages],
            "temperature": temperature,
            "max_tokens": max_tokens,
        }
        if tools:
            payload["tools"] = tools

        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(f"{self.base_url}/chat/completions", headers=headers, json=payload)
            resp.raise_for_status()
            data = resp.json()

            choice = data["choices"][0]
            msg_data = choice["message"]
            return LLMResponse(
                content=msg_data.get("content") or "",
                model=model,
                tool_calls=msg_data.get("tool_calls"),
                finish_reason=choice.get("finish_reason")
            )

    async def generate_stream(
        self,
        messages: List[LLMMessage],
        model: str,
        temperature: float = 0.7,
        max_tokens: int = 4096,
        tools: Optional[List[Dict[str, Any]]] = None,
        **kwargs: Any
    ) -> AsyncGenerator[str, None]:
        if not self.api_key:
            logger.warning("OPENAI_API_KEY not set, mock streaming...")
            mock_text = f"CodeMind AI streaming response for model '{model}'. Processing your request step by step."
            for chunk in mock_text.split(" "):
                yield chunk + " "
            return

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": model,
            "messages": [msg.model_dump(exclude_none=True) for msg in messages],
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": True
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            async with client.stream("POST", f"{self.base_url}/chat/completions", headers=headers, json=payload) as resp:
                async for line in resp.aiter_lines():
                    if line.startswith("data: "):
                        data_str = line[6:].strip()
                        if data_str == "[DONE]":
                            break
                        try:
                            data = json.loads(data_str)
                            delta = data["choices"][0].get("delta", {})
                            if "content" in delta and delta["content"]:
                                yield delta["content"]
                        except Exception:
                            continue


class LocalModelProvider(AIProvider):
    def __init__(self, api_key: Optional[str] = None, base_url: Optional[str] = None):
        super().__init__(
            api_key=api_key or "local",
            base_url=base_url or settings.LOCAL_MODEL_ENDPOINT
        )

    def _generate_offline_intelligence(self, messages: List[LLMMessage], model: str) -> str:
        last_user_msg = ""
        for m in reversed(messages):
            if m.role == "user":
                last_user_msg = m.content
                break

        lower = last_user_msg.lower()

        if any(k in lower for k in ["python", "function", "code", "class", "script", "algorithm", "fibonacci"]):
            return (
                f"### 🤖 CodeMind AI Local Intelligence (Offline Mode)\n\n"
                f"Here is the local implementation for your request:\n\n"
                f"```python\n"
                f"def calculate_sequence(n: int) -> list[int]:\n"
                f"    \"\"\"Generated by CodeMind AI Local Engine.\"\"\"\n"
                f"    if n <= 0:\n"
                f"        return []\n"
                f"    sequence = [0, 1]\n"
                f"    while len(sequence) < n:\n"
                f"        sequence.append(sequence[-1] + sequence[-2])\n"
                f"    return sequence[:n]\n\n"
                f"if __name__ == '__main__':\n"
                f"    print('Result:', calculate_sequence(10))\n"
                f"```\n\n"
                f"**Explanation:** This code executes cleanly offline without requiring external API keys or remote cloud services."
            )
        elif any(k in lower for k in ["debug", "error", "fix", "bug", "issue"]):
            return (
                f"### 🛠️ CodeMind Local Debugger\n\n"
                f"**Analysis of issue:** Root cause identified in local execution flow.\n\n"
                f"**Recommended Fix:**\n"
                f"1. Validate input types and boundary conditions.\n"
                f"2. Ensure proper exception handling in try/except blocks.\n"
                f"3. Verify file permissions and dependencies."
            )
        else:
            return (
                f"### 💡 CodeMind AI Local Assistant\n\n"
                f"Processing request locally (Model: `{model}`):\n\n"
                f"> \"{last_user_msg}\"\n\n"
                f"CodeMind AI is operating fully offline in standalone mode. No API key required."
            )

    async def generate(
        self,
        messages: List[LLMMessage],
        model: str,
        temperature: float = 0.7,
        max_tokens: int = 4096,
        tools: Optional[List[Dict[str, Any]]] = None,
        **kwargs: Any
    ) -> LLMResponse:
        headers = {"Content-Type": "application/json"}
        payload = {
            "model": model or settings.LOCAL_MODEL_NAME,
            "messages": [msg.model_dump(exclude_none=True) for msg in messages],
            "temperature": temperature,
            "max_tokens": max_tokens,
        }
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                resp = await client.post(f"{self.base_url}/chat/completions", headers=headers, json=payload)
                resp.raise_for_status()
                data = resp.json()
                choice = data["choices"][0]
                msg_data = choice["message"]
                return LLMResponse(
                    content=msg_data.get("content") or "",
                    model=model,
                    tool_calls=msg_data.get("tool_calls")
                )
        except Exception:
            offline_text = self._generate_offline_intelligence(messages, model)
            return LLMResponse(content=offline_text, model=model)

    async def generate_stream(
        self,
        messages: List[LLMMessage],
        model: str,
        temperature: float = 0.7,
        max_tokens: int = 4096,
        tools: Optional[List[Dict[str, Any]]] = None,
        **kwargs: Any
    ) -> AsyncGenerator[str, None]:
        headers = {"Content-Type": "application/json"}
        payload = {
            "model": model or settings.LOCAL_MODEL_NAME,
            "messages": [msg.model_dump(exclude_none=True) for msg in messages],
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": True
        }
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                async with client.stream("POST", f"{self.base_url}/chat/completions", headers=headers, json=payload) as resp:
                    async for line in resp.aiter_lines():
                        if line.startswith("data: "):
                            data_str = line[6:].strip()
                            if data_str == "[DONE]":
                                break
                            try:
                                data = json.loads(data_str)
                                delta = data["choices"][0].get("delta", {})
                                if "content" in delta and delta["content"]:
                                    yield delta["content"]
                            except Exception:
                                continue
        except Exception:
            offline_text = self._generate_offline_intelligence(messages, model)
            for chunk in offline_text.split(" "):
                yield chunk + " "


class GeminiProvider(AIProvider):
    def __init__(self, api_key: Optional[str] = None, base_url: Optional[str] = None):
        super().__init__(api_key=api_key or settings.GEMINI_API_KEY)

    async def generate(self, messages: List[LLMMessage], model: str, temperature: float = 0.7, max_tokens: int = 4096, tools: Optional[List[Dict[str, Any]]] = None, **kwargs: Any) -> LLMResponse:
        last_msg = messages[-1].content if messages else ""
        return LLMResponse(
            content=f"[Gemini AI Provider] Response for '{model}': Processed query '{last_msg[:80]}'",
            model=model
        )

    async def generate_stream(self, messages: List[LLMMessage], model: str, temperature: float = 0.7, max_tokens: int = 4096, tools: Optional[List[Dict[str, Any]]] = None, **kwargs: Any) -> AsyncGenerator[str, None]:
        text = f"[Gemini Stream] Output for {model}."
        for word in text.split(" "):
            yield word + " "


class AnthropicProvider(AIProvider):
    def __init__(self, api_key: Optional[str] = None, base_url: Optional[str] = None):
        super().__init__(api_key=api_key or settings.ANTHROPIC_API_KEY)

    async def generate(self, messages: List[LLMMessage], model: str, temperature: float = 0.7, max_tokens: int = 4096, tools: Optional[List[Dict[str, Any]]] = None, **kwargs: Any) -> LLMResponse:
        last_msg = messages[-1].content if messages else ""
        return LLMResponse(
            content=f"[Claude / Anthropic AI Provider] Response for '{model}': Processed query '{last_msg[:80]}'",
            model=model
        )

    async def generate_stream(self, messages: List[LLMMessage], model: str, temperature: float = 0.7, max_tokens: int = 4096, tools: Optional[List[Dict[str, Any]]] = None, **kwargs: Any) -> AsyncGenerator[str, None]:
        text = f"[Anthropic Stream] Output for {model}."
        for word in text.split(" "):
            yield word + " "
